### ISSUE TITLE
All values are written on one line

### ISSUE THREAD

**Issue by johnnymast** [oohology/dotenvwriter#3]
Hi im back!,

The latest update breaks my installation. This is what it creates when using ->set and ->save()

APP_ENV=localAPP_KEY=base64:lWS7HdYF416X8aU/0BHSP5ZeXyTw0u/E/AmI1EdbkEU=APP_DEBUG=trueAPP_LOG_LEVEL=debugAPP_URL=http://localhostDB_CONNECTION=sqliteBROADCAST_DRIVER=logCACHE_DRIVER=fileSESSION_DRIVER=fileQUEUE_DRIVER=sync

**Comment by davidwoodmansee** [comment]
Ok, sorry about that. The regexes I used to match the keys seems to be more sensitive to windows line endings than I expected. I should be able to spend some more time on it in a few hours. Do the tests still fail on your system? I was able to get everything to pass on Windows 10.

**Comment by johnnymast** [comment]
Let me test it for you.

**Comment by davidwoodmansee** [comment]
I just glanced at the code and something jumped out at me. I don't think I have any tests that cover initializing a new file. When it starts writing to an empty file it never auto-detects the line endings and that's where it fell apart. I just pushed a change as v1.2.3 that fixed that scenario for me on Win10

**Comment by johnnymast** [comment]
johnny@DESKTOP-J9E32CC MINGW64 ~/Downloads/dotenvwriter-master (1)/dotenvwriter-master
$ phpunit
PHPUnit 5.7.17 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.0.13
Configuration: C:\Users\johnny\Downloads\dotenvwriter-master (1)\dotenvwriter-master\phpunit.xml.dist

.........                                                           9 / 9 (100%)

Time: 85 ms, Memory: 4.00MB

OK (9 tests, 37 assertions)

johnny@DESKTOP-J9E32CC MINGW64 ~/Downloads/dotenvwriter-master (1)/dotenvwriter-master

**Comment by johnnymast** [comment]
It does but maybe your now checking for \n's and not \r\n ?

**Comment by johnnymast** [comment]
BTW if you wonder where your project is used. Its here https://github.com/johnnymast/myio

**Comment by johnnymast** [comment]
I had to scale it back to 1.6 after that it didn't work all of a sudden. But that could be composer cache as well.

**Comment by davidwoodmansee** [comment]
Can you test the latest version 1.2.3 and see if it solves the issue? I think it was just the issue with it initializing a blank .env file that I mentioned above, and now it works for me in that scenario on Win10 and Ubuntu and passes the tests on both platforms.

**Comment by johnnymast** [comment]
Yes one moment

**Comment by johnnymast** [comment]
It seems to be working.

Code: 
![image](https://cloud.githubusercontent.com/assets/121194/24268417/03dc43bc-100e-11e7-9994-92f5b73fe0cd.png)

Result:
![image](https://cloud.githubusercontent.com/assets/121194/24268454/1dcd4cf8-100e-11e7-8bdd-9cd5250b252d.png)

Tests:
![image](https://cloud.githubusercontent.com/assets/121194/24268487/39bc5d00-100e-11e7-9cc9-d5d61c1facf0.png)

**Comment by davidwoodmansee** [comment]
That's great. Thank you!
