### ISSUE TITLE
Boolean is not stored correctly

### ISSUE THREAD

**Issue by shadoWalker89** [oohology/dotenvwriter#4]
Hi when i do 

```php
$writer->set('key', true);
```

In the .env file i will have

```
key=1
```

If i do

```php
$writer->set('key', false);
```

In the .env file i will have

```
key=
```

For now to store booleans i must have to pass the string "true" and "false"

```php
$writer->set('key', "true");
$writer->set('key', "false");
```

I opened a PR to fix this https://github.com/oohology/dotenvwriter/pull/5

**Comment by davidwoodmansee** [comment]
This is similar to an issue discussed on vlucas/phpdotenv here - https://github.com/vlucas/phpdotenv/issues/104. Basically they decided when reading/writing the .env file it should stay closer to shell behavior, and leave the interpretation that (string)"true" and (boolean)true are equivalent as the responsibility of the app. In the case of Laravel, what it gets back from DotEnv is just the string "true", but then laravel's `env()` method converts it to a boolean as seen here - https://github.com/laravel/framework/blob/8c614010648bffb8bc24c3b532db08619e9a5983/src/Illuminate/Foundation/helpers.php#L626

However, I can see the usefulness for Laravel or other frameworks that follow this behavior, so I would be receptive to this PR if you made it an optional feature that could be enabled at run-time, e.g.
```
(new DotEnvWriter('../.env'))
    ->castBooleans()
    ->set('BOOL_VALUE', true)
    ->save();
// result: BOOL_VALUE=true
```
vs. the original/default behavior
```
(new DotEnvWriter('../.env'))
    ->set('BOOL_VALUE', true)
    ->save();
// result: BOOL_VALUE=1
```

**Comment by shadoWalker89** [comment]
Updated the PR
